AWSTemplateFormatVersion: "2010-09-09"
Description: >
    se Crea un VPC con dos bases de Datos internas
    en subredes publicas.

Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.1.0/24
            EnableDnsSupport: true
            EnableDnsHostnames: true
    
    SubnetMySQL:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
    
    SubnetPostgres:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
    
    SubnetPrivate1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            MapPublicIpOnLaunch: false

    SubnetPrivate2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            MapPublicIpOnLaunch: false

    InternetGateway:
      Type: AWS::EC2::InternetGateway
    
    VPCGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
          VpcId: !Ref VPC
          InternetGatewayId: !Ref InternetGateway

    SubnetRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref VPC

    SubnetMySQLRoute:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref SubnetRouteTable
            SubnetId: !Ref SubnetMySQL
    
    SubnetPostgresRoute:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref SubnetRouteTable
            SubnetId: !Ref SubnetPostgres

    InternetGatewayRoute:
        Type: AWS::EC2::Route
        DependsOn: !Ref VPCGatewayAttachment
        Properties:
            RouteTableId: !Ref SubnetRouteTable
            GatewayId: !Ref InternetGateway
    
    SecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        VpcId: !Ref VPC
        GroupName: VPC-DMS
        GroupDescription: Default Security Group VPC
        SecurityGroupIngress:
            - IpProtocol: tcp
              CidrIp: 0.0.0.0/0
              FromPort: 3306
              ToPort: 3306
            - IpProtocol: tcp
              CidrIp: 0.0.0.0/0
              FromPort: 5432
              ToPort: 5432
        
